/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.portalsystem;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;


/**
 *
 * @author Windows
 */

public class login extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public static int baseStudentNumber;
    
    public login() {
        initComponents();
        con = dbConnection.connectionDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginUser = new javax.swing.JTextField();
        loginPass = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        loginLoginBtn = new javax.swing.JButton();
        loginRegBtn = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        errorMsgText = new javax.swing.JLabel();
        loginRegBtn_label = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scholarship Portal");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(416, 533));
        setPreferredSize(new java.awt.Dimension(415, 525));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 480));
        getContentPane().setLayout(null);

        loginUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginUser.setForeground(new java.awt.Color(153, 153, 153));
        loginUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        loginUser.setText("Student Number or Student Email");
        loginUser.setToolTipText("");
        loginUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        loginUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUserFocusLost(evt);
            }
        });
        loginUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginUserMouseExited(evt);
            }
        });
        loginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserActionPerformed(evt);
            }
        });
        getContentPane().add(loginUser);
        loginUser.setBounds(100, 180, 200, 37);

        loginPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginPass.setForeground(new java.awt.Color(153, 153, 153));
        loginPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        loginPass.setText("Password");
        loginPass.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        loginPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginPassFocusLost(evt);
            }
        });
        loginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPassActionPerformed(evt);
            }
        });
        getContentPane().add(loginPass);
        loginPass.setBounds(100, 230, 200, 37);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(80, 50, 240, 110);

        loginLoginBtn.setBackground(new java.awt.Color(0, 51, 102));
        loginLoginBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginLoginBtn.setText("Login");
        loginLoginBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginLoginBtn.setFocusPainted(false);
        loginLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginLoginBtn);
        loginLoginBtn.setBounds(150, 280, 100, 30);

        loginRegBtn.setBackground(new java.awt.Color(0, 51, 102));
        loginRegBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginRegBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginRegBtn.setText("Register");
        loginRegBtn.setBorder(null);
        loginRegBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginRegBtn.setFocusPainted(false);
        loginRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRegBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginRegBtn);
        loginRegBtn.setBounds(160, 420, 80, 20);

        copyright.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("© Copyright 2024 #include <iostream> | Scholarship Portal");
        getContentPane().add(copyright);
        copyright.setBounds(0, 460, 400, 20);

        errorMsgText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        errorMsgText.setForeground(new java.awt.Color(200, 0, 0));
        errorMsgText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMsgText.setText(" ");
        errorMsgText.setAlignmentY(0.0F);
        getContentPane().add(errorMsgText);
        errorMsgText.setBounds(100, 320, 200, 20);

        loginRegBtn_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginRegBtn_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginRegBtn_label.setText("Don't have an account?");
        loginRegBtn_label.setAlignmentY(0.0F);
        getContentPane().add(loginRegBtn_label);
        loginRegBtn_label.setBounds(130, 400, 140, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbg.jpg"))); // NOI18N
        bg.setText("jLabel7");
        bg.setMaximumSize(new java.awt.Dimension(0, 0));
        bg.setMinimumSize(new java.awt.Dimension(0, 0));
        bg.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 400, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLoginBtnActionPerformed
        LineBorder coloredBorderRed = new LineBorder(Color.RED, 1);
        LineBorder coloredBorderBlk = new LineBorder(Color.BLACK, 1);
        EmptyBorder paddingBorder = new EmptyBorder(1, 5, 1, 1);
        
        // if user entered empty credentials in the text boxes
        if(loginUser.getText().equals("Student Number or Student Email") && loginPass.getText().equals("Password")) {
            errorMsgText.setText("You entered empty credentials.");
            
            loginUser.setBorder(new CompoundBorder(coloredBorderRed, paddingBorder));
            loginPass.setBorder(new CompoundBorder(coloredBorderRed, paddingBorder));
        }
        
        // if user entered empty username in the username field
        else if(loginUser.getText().equals("Student Number or Student Email")) {
            errorMsgText.setText("Username is empty.");
            
            loginUser.setBorder(new CompoundBorder(coloredBorderRed, paddingBorder));
            loginPass.setBorder(new CompoundBorder(coloredBorderBlk, paddingBorder));
        }
        
        // if user entered empty password in the password field
        else if(loginPass.getText().equals("Password")) {
            errorMsgText.setText("Password is empty.");
            
            loginUser.setBorder(new CompoundBorder(coloredBorderBlk, paddingBorder));
            loginPass.setBorder(new CompoundBorder(coloredBorderRed, paddingBorder));
        }
        
        else {
            errorMsgText.setText("");
            
            loginUser.setBorder(new CompoundBorder(coloredBorderBlk, paddingBorder));
            loginPass.setBorder(new CompoundBorder(coloredBorderBlk, paddingBorder));
            
            // sql accounts checking from database
            String sql = "SELECT * from student WHERE student_number = ? OR email = ? AND password = ?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, loginUser.getText());
                pst.setString(2, loginUser.getText());
                pst.setString(3, loginPass.getText());
                rs = pst.executeQuery();
                
                if(rs.next()) { // login successful
                    // show dashboard
                    baseStudentNumber = rs.getInt("user_id");
                    
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new dashboard().setVisible(true);
                        }
                    });

                    dispose();
                }
                
                else errorMsgText.setText("Incorrect credentials."); // login failed
            }
            catch(SQLException ex) {
                ex.printStackTrace();
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_loginLoginBtnActionPerformed

    private void loginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPassActionPerformed

    private void loginPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPassFocusLost
        if(loginPass.getText().equals("")) {
            loginPass.setText("Password");
            loginPass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_loginPassFocusLost

    private void loginPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPassFocusGained
        if(loginPass.getText().equals("Password")) {
            loginPass.setText("");
            loginPass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_loginPassFocusGained

    private void loginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserActionPerformed

    private void loginUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserFocusLost
        if(loginUser.getText().equals("")) {
            loginUser.setText("Student Number or Student Email");
            loginUser.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_loginUserFocusLost

    private void loginUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserFocusGained
        if(loginUser.getText().equals("Student Number or Student Email")) {
            loginUser.setText("");
            loginUser.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_loginUserFocusGained

    private void loginRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRegBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
        
        dispose();
    }//GEN-LAST:event_loginRegBtnActionPerformed

    private void loginUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUserMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserMouseExited

    private void regStNumberFocusGained(java.awt.event.FocusEvent evt) {                                        
        // wala
    }                                       

    private void regStNumberFocusLost(java.awt.event.FocusEvent evt) {                                      
        // wala
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel errorMsgText;
    private javax.swing.JButton loginLoginBtn;
    private javax.swing.JTextField loginPass;
    private javax.swing.JButton loginRegBtn;
    private javax.swing.JLabel loginRegBtn_label;
    private javax.swing.JTextField loginUser;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
