/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.portalsystem;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.border.*;

/**
 *
 * @author Windows
 */
public class register extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public register() {
        initComponents();
        con = dbConnection.connectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regTitle = new javax.swing.JLabel();
        regStudNum_label = new javax.swing.JLabel();
        regStudNum = new javax.swing.JTextField();
        regAddress_label = new javax.swing.JLabel();
        regBirthday_year = new javax.swing.JTextField();
        regBirthday_month = new javax.swing.JTextField();
        regBirthday_day = new javax.swing.JTextField();
        regFirstName = new javax.swing.JTextField();
        regFirstName_label = new javax.swing.JLabel();
        regMidName = new javax.swing.JTextField();
        regMidName_label = new javax.swing.JLabel();
        regLastName_label = new javax.swing.JLabel();
        regAddress = new javax.swing.JTextField();
        regBirthday_label = new javax.swing.JLabel();
        regGender_label = new javax.swing.JLabel();
        regGender = new javax.swing.JComboBox<>();
        regLastName = new javax.swing.JTextField();
        regEmail = new javax.swing.JTextField();
        regEmail_label = new javax.swing.JLabel();
        regPhone = new javax.swing.JTextField();
        regPhone_label = new javax.swing.JLabel();
        regReligion = new javax.swing.JTextField();
        regReligion_label = new javax.swing.JLabel();
        regCitizenship_label = new javax.swing.JLabel();
        regCitizenship = new javax.swing.JTextField();
        regCivilStat_label = new javax.swing.JLabel();
        regCivilStatus = new javax.swing.JComboBox<>();
        regGuardian_label = new javax.swing.JLabel();
        regGuardian = new javax.swing.JTextField();
        regSignUpBtn = new javax.swing.JButton();
        regLogin_label = new javax.swing.JLabel();
        regLogin = new javax.swing.JButton();
        regCopyright = new javax.swing.JLabel();
        regPassword = new javax.swing.JTextField();
        regPassword_label = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(9999, 9999));
        setMinimumSize(new java.awt.Dimension(504, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        regTitle.setFont(new java.awt.Font("Californian FB", 1, 35)); // NOI18N
        regTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regTitle.setText("REGISTRATION");
        regTitle.setToolTipText("");
        getContentPane().add(regTitle);
        regTitle.setBounds(0, 50, 490, 40);

        regStudNum_label.setText("Student Number:");
        getContentPane().add(regStudNum_label);
        regStudNum_label.setBounds(20, 110, 120, 16);

        regStudNum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regStudNum.setForeground(new java.awt.Color(153, 153, 153));
        regStudNum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regStudNum.setText("Enter student number");
        regStudNum.setToolTipText("");
        regStudNum.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regStudNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regStudNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regStudNumFocusLost(evt);
            }
        });
        regStudNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regStudNumMouseExited(evt);
            }
        });
        regStudNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStudNumActionPerformed(evt);
            }
        });
        getContentPane().add(regStudNum);
        regStudNum.setBounds(20, 130, 200, 37);

        regAddress_label.setText("Address:");
        getContentPane().add(regAddress_label);
        regAddress_label.setBounds(20, 520, 120, 16);

        regBirthday_year.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regBirthday_year.setForeground(new java.awt.Color(153, 153, 153));
        regBirthday_year.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regBirthday_year.setText("YYYY");
        regBirthday_year.setToolTipText("");
        regBirthday_year.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regBirthday_year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regBirthday_yearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regBirthday_yearFocusLost(evt);
            }
        });
        regBirthday_year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regBirthday_yearMouseExited(evt);
            }
        });
        regBirthday_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBirthday_yearActionPerformed(evt);
            }
        });
        getContentPane().add(regBirthday_year);
        regBirthday_year.setBounds(160, 410, 60, 37);

        regBirthday_month.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regBirthday_month.setForeground(new java.awt.Color(153, 153, 153));
        regBirthday_month.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regBirthday_month.setText("MM");
        regBirthday_month.setToolTipText("");
        regBirthday_month.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regBirthday_month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regBirthday_monthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regBirthday_monthFocusLost(evt);
            }
        });
        regBirthday_month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regBirthday_monthMouseExited(evt);
            }
        });
        regBirthday_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBirthday_monthActionPerformed(evt);
            }
        });
        getContentPane().add(regBirthday_month);
        regBirthday_month.setBounds(20, 410, 60, 37);

        regBirthday_day.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regBirthday_day.setForeground(new java.awt.Color(153, 153, 153));
        regBirthday_day.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regBirthday_day.setText("DD");
        regBirthday_day.setToolTipText("");
        regBirthday_day.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regBirthday_day.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regBirthday_dayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regBirthday_dayFocusLost(evt);
            }
        });
        regBirthday_day.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regBirthday_dayMouseExited(evt);
            }
        });
        regBirthday_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBirthday_dayActionPerformed(evt);
            }
        });
        getContentPane().add(regBirthday_day);
        regBirthday_day.setBounds(90, 410, 60, 37);

        regFirstName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regFirstName.setForeground(new java.awt.Color(153, 153, 153));
        regFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regFirstName.setText("Enter first name");
        regFirstName.setToolTipText("");
        regFirstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regFirstNameFocusLost(evt);
            }
        });
        regFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFirstNameMouseExited(evt);
            }
        });
        regFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(regFirstName);
        regFirstName.setBounds(20, 200, 200, 37);

        regFirstName_label.setText("First Name:");
        getContentPane().add(regFirstName_label);
        regFirstName_label.setBounds(20, 180, 120, 16);

        regMidName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regMidName.setForeground(new java.awt.Color(153, 153, 153));
        regMidName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regMidName.setText("Enter middle name");
        regMidName.setToolTipText("");
        regMidName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regMidName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regMidNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regMidNameFocusLost(evt);
            }
        });
        regMidName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regMidNameMouseExited(evt);
            }
        });
        regMidName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMidNameActionPerformed(evt);
            }
        });
        getContentPane().add(regMidName);
        regMidName.setBounds(20, 270, 200, 37);

        regMidName_label.setText("Middle Name:");
        getContentPane().add(regMidName_label);
        regMidName_label.setBounds(20, 250, 120, 16);

        regLastName_label.setText("Last Name:");
        getContentPane().add(regLastName_label);
        regLastName_label.setBounds(20, 320, 120, 16);

        regAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regAddress.setForeground(new java.awt.Color(153, 153, 153));
        regAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regAddress.setText("Enter address");
        regAddress.setToolTipText("");
        regAddress.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regAddressFocusLost(evt);
            }
        });
        regAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regAddressMouseExited(evt);
            }
        });
        regAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAddressActionPerformed(evt);
            }
        });
        getContentPane().add(regAddress);
        regAddress.setBounds(20, 540, 200, 37);

        regBirthday_label.setText("Date of Birth:");
        getContentPane().add(regBirthday_label);
        regBirthday_label.setBounds(20, 390, 120, 16);

        regGender_label.setText("Gender on Birth:");
        getContentPane().add(regGender_label);
        regGender_label.setBounds(20, 460, 120, 16);

        regGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Select gender]", "Male", "Female" }));
        regGender.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        getContentPane().add(regGender);
        regGender.setBounds(20, 480, 200, 30);

        regLastName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regLastName.setForeground(new java.awt.Color(153, 153, 153));
        regLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regLastName.setText("Enter last name");
        regLastName.setToolTipText("");
        regLastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regLastNameFocusLost(evt);
            }
        });
        regLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regLastNameMouseExited(evt);
            }
        });
        regLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(regLastName);
        regLastName.setBounds(20, 340, 200, 37);

        regEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regEmail.setForeground(new java.awt.Color(153, 153, 153));
        regEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regEmail.setText("Enter email address");
        regEmail.setToolTipText("");
        regEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regEmailFocusLost(evt);
            }
        });
        regEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regEmailMouseExited(evt);
            }
        });
        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });
        getContentPane().add(regEmail);
        regEmail.setBounds(260, 130, 200, 37);

        regEmail_label.setText("Email Address:");
        getContentPane().add(regEmail_label);
        regEmail_label.setBounds(260, 110, 120, 16);

        regPhone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regPhone.setForeground(new java.awt.Color(153, 153, 153));
        regPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regPhone.setText("Enter phone no.");
        regPhone.setToolTipText("");
        regPhone.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regPhoneFocusLost(evt);
            }
        });
        regPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regPhoneMouseExited(evt);
            }
        });
        regPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(regPhone);
        regPhone.setBounds(260, 200, 200, 37);

        regPhone_label.setText("Phone No.:");
        getContentPane().add(regPhone_label);
        regPhone_label.setBounds(260, 180, 120, 16);

        regReligion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regReligion.setForeground(new java.awt.Color(153, 153, 153));
        regReligion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regReligion.setText("Enter religion");
        regReligion.setToolTipText("");
        regReligion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regReligion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regReligionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regReligionFocusLost(evt);
            }
        });
        regReligion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regReligionMouseExited(evt);
            }
        });
        regReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regReligionActionPerformed(evt);
            }
        });
        getContentPane().add(regReligion);
        regReligion.setBounds(260, 270, 200, 37);

        regReligion_label.setText("Religion:");
        getContentPane().add(regReligion_label);
        regReligion_label.setBounds(260, 250, 120, 16);

        regCitizenship_label.setText("Citizenship:");
        getContentPane().add(regCitizenship_label);
        regCitizenship_label.setBounds(260, 320, 120, 16);

        regCitizenship.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regCitizenship.setForeground(new java.awt.Color(153, 153, 153));
        regCitizenship.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regCitizenship.setText("Enter citizenship");
        regCitizenship.setToolTipText("");
        regCitizenship.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regCitizenship.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regCitizenshipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regCitizenshipFocusLost(evt);
            }
        });
        regCitizenship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regCitizenshipMouseExited(evt);
            }
        });
        regCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCitizenshipActionPerformed(evt);
            }
        });
        getContentPane().add(regCitizenship);
        regCitizenship.setBounds(260, 340, 200, 37);

        regCivilStat_label.setText("Civil Status:");
        getContentPane().add(regCivilStat_label);
        regCivilStat_label.setBounds(260, 390, 120, 16);

        regCivilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Select civil status]", "Single", "Married", "Widowed" }));
        regCivilStatus.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        getContentPane().add(regCivilStatus);
        regCivilStatus.setBounds(260, 410, 200, 30);

        regGuardian_label.setText("Guardian:");
        getContentPane().add(regGuardian_label);
        regGuardian_label.setBounds(260, 450, 120, 16);

        regGuardian.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regGuardian.setForeground(new java.awt.Color(153, 153, 153));
        regGuardian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regGuardian.setText("Enter guardian's name");
        regGuardian.setToolTipText("");
        regGuardian.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regGuardian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regGuardianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regGuardianFocusLost(evt);
            }
        });
        regGuardian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regGuardianMouseExited(evt);
            }
        });
        regGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regGuardianActionPerformed(evt);
            }
        });
        getContentPane().add(regGuardian);
        regGuardian.setBounds(260, 470, 200, 37);

        regSignUpBtn.setBackground(new java.awt.Color(0, 51, 102));
        regSignUpBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regSignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        regSignUpBtn.setText("Sign Up");
        regSignUpBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regSignUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regSignUpBtn.setFocusPainted(false);
        regSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSignUpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regSignUpBtn);
        regSignUpBtn.setBounds(190, 590, 100, 30);

        regLogin_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regLogin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLogin_label.setText("Already registered?");
        regLogin_label.setAlignmentY(0.0F);
        getContentPane().add(regLogin_label);
        regLogin_label.setBounds(170, 630, 140, 20);

        regLogin.setBackground(new java.awt.Color(0, 51, 102));
        regLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regLogin.setForeground(new java.awt.Color(255, 255, 255));
        regLogin.setText("Login");
        regLogin.setBorder(null);
        regLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regLogin.setFocusPainted(false);
        regLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLoginActionPerformed(evt);
            }
        });
        getContentPane().add(regLogin);
        regLogin.setBounds(200, 650, 80, 20);

        regCopyright.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        regCopyright.setForeground(new java.awt.Color(255, 255, 255));
        regCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regCopyright.setText("© Copyright 2024 #include <iostream> | Scholarship Portal");
        getContentPane().add(regCopyright);
        regCopyright.setBounds(0, 690, 490, 20);

        regPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        regPassword.setForeground(new java.awt.Color(153, 153, 153));
        regPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regPassword.setText("Enter password");
        regPassword.setToolTipText("");
        regPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        regPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regPasswordFocusLost(evt);
            }
        });
        regPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regPasswordMouseExited(evt);
            }
        });
        regPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(regPassword);
        regPassword.setBounds(260, 540, 200, 37);

        regPassword_label.setText("Password:");
        getContentPane().add(regPassword_label);
        regPassword_label.setBounds(260, 520, 120, 16);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regbg.jpg"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 490, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regStudNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regStudNumFocusGained
        if(regStudNum.getText().equals("Enter student number")) {
            regStudNum.setText("");
            regStudNum.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regStudNumFocusGained

    private void regStudNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regStudNumFocusLost
        if(regStudNum.getText().equals("")) {
            regStudNum.setText("Enter student number");
            regStudNum.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regStudNumFocusLost

    private void regStudNumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regStudNumMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regStudNumMouseExited

    private void regStudNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStudNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regStudNumActionPerformed

    private void regBirthday_yearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_yearFocusGained
        if(regBirthday_year.getText().equals("YYYY")) {
            regBirthday_year.setText("");
            regBirthday_year.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regBirthday_yearFocusGained

    private void regBirthday_yearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_yearFocusLost
        if(regBirthday_year.getText().equals("")) {
            regBirthday_year.setText("YYYY");
            regBirthday_year.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regBirthday_yearFocusLost

    private void regBirthday_yearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBirthday_yearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_yearMouseExited

    private void regBirthday_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBirthday_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_yearActionPerformed

    private void regBirthday_monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_monthFocusGained
        if(regBirthday_month.getText().equals("MM")) {
            regBirthday_month.setText("");
            regBirthday_month.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regBirthday_monthFocusGained

    private void regBirthday_monthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_monthFocusLost
        if(regBirthday_month.getText().equals("")) {
            regBirthday_month.setText("MM");
            regBirthday_month.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regBirthday_monthFocusLost

    private void regBirthday_monthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBirthday_monthMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_monthMouseExited

    private void regBirthday_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBirthday_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_monthActionPerformed

    private void regBirthday_dayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_dayFocusGained
        if(regBirthday_day.getText().equals("DD")) {
            regBirthday_day.setText("");
            regBirthday_day.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regBirthday_dayFocusGained

    private void regBirthday_dayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regBirthday_dayFocusLost
        if(regBirthday_day.getText().equals("")) {
            regBirthday_day.setText("DD");
            regBirthday_day.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regBirthday_dayFocusLost

    private void regBirthday_dayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBirthday_dayMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_dayMouseExited

    private void regBirthday_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBirthday_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regBirthday_dayActionPerformed

    private void regFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusGained
        if(regFirstName.getText().equals("Enter first name")) {
            regFirstName.setText("");
            regFirstName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regFirstNameFocusGained

    private void regFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusLost
        if(regFirstName.getText().equals("")) {
            regFirstName.setText("Enter first name");
            regFirstName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regFirstNameFocusLost

    private void regFirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFirstNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regFirstNameMouseExited

    private void regFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regFirstNameActionPerformed

    private void regMidNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regMidNameFocusGained
        if(regMidName.getText().equals("Enter middle name")) {
            regMidName.setText("");
            regMidName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regMidNameFocusGained

    private void regMidNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regMidNameFocusLost
        if(regMidName.getText().equals("")) {
            regMidName.setText("Enter middle name");
            regMidName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regMidNameFocusLost

    private void regMidNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMidNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regMidNameMouseExited

    private void regMidNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMidNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMidNameActionPerformed

    private void regAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regAddressFocusGained
        if(regAddress.getText().equals("Enter address")) {
            regAddress.setText("");
            regAddress.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regAddressFocusGained

    private void regAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regAddressFocusLost
        if(regAddress.getText().equals("")) {
            regAddress.setText("Enter address");
            regAddress.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regAddressFocusLost

    private void regAddressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regAddressMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regAddressMouseExited

    private void regAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regAddressActionPerformed

    private void regLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusGained
        if(regLastName.getText().equals("Enter last name")) {
            regLastName.setText("");
            regLastName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regLastNameFocusGained

    private void regLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusLost
        if(regLastName.getText().equals("")) {
            regLastName.setText("Enter last name");
            regLastName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regLastNameFocusLost

    private void regLastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regLastNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regLastNameMouseExited

    private void regLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regLastNameActionPerformed

    private void regEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regEmailFocusGained
        if(regEmail.getText().equals("Enter email address")) {
            regEmail.setText("");
            regEmail.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regEmailFocusGained

    private void regEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regEmailFocusLost
        if(regEmail.getText().equals("")) {
            regEmail.setText("Enter email address");
            regEmail.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regEmailFocusLost

    private void regEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regEmailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailMouseExited

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void regPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPhoneFocusGained
        if(regPhone.getText().equals("Enter phone no.")) {
            regPhone.setText("");
            regPhone.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regPhoneFocusGained

    private void regPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPhoneFocusLost
        if(regPhone.getText().equals("")) {
            regPhone.setText("Enter phone no.");
            regPhone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regPhoneFocusLost

    private void regPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPhoneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regPhoneMouseExited

    private void regPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPhoneActionPerformed

    private void regReligionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regReligionFocusGained
        if(regReligion.getText().equals("Enter religion")) {
            regReligion.setText("");
            regReligion.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regReligionFocusGained

    private void regReligionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regReligionFocusLost
        if(regReligion.getText().equals("")) {
            regReligion.setText("Enter religion");
            regReligion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regReligionFocusLost

    private void regReligionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regReligionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regReligionMouseExited

    private void regReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regReligionActionPerformed

    private void regCitizenshipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regCitizenshipFocusGained
        if(regCitizenship.getText().equals("Enter citizenship")) {
            regCitizenship.setText("");
            regCitizenship.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regCitizenshipFocusGained

    private void regCitizenshipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regCitizenshipFocusLost
        if(regCitizenship.getText().equals("")) {
            regCitizenship.setText("Enter citizenship");
            regCitizenship.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regCitizenshipFocusLost

    private void regCitizenshipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regCitizenshipMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regCitizenshipMouseExited

    private void regCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regCitizenshipActionPerformed

    private void regGuardianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regGuardianFocusGained
        if(regGuardian.getText().equals("Enter guardian's name")) {
            regGuardian.setText("");
            regGuardian.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regGuardianFocusGained

    private void regGuardianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regGuardianFocusLost
        if(regGuardian.getText().equals("")) {
            regGuardian.setText("Enter guardian's name");
            regGuardian.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regGuardianFocusLost

    private void regGuardianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regGuardianMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regGuardianMouseExited

    private void regGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regGuardianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regGuardianActionPerformed

    private void regSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSignUpBtnActionPerformed
        try {
            // get the information from database
            String sql = "INSERT INTO student (student_number, first_name, middle_name, last_name, email, birth_date, gender, phone_number, address, religion, citizenship, civil_status, guardian, password) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
            pst = con.prepareStatement(sql);
            pst.setString(1, regStudNum.getText());
            pst.setString(2, regFirstName.getText());
            pst.setString(3, regMidName.getText());
            pst.setString(4, regLastName.getText());
            pst.setString(5, regEmail.getText());
            
            String birthdate = regBirthday_month.getText() + "/" + regBirthday_day.getText() + "/" + regBirthday_year.getText();
            pst.setString(6, birthdate);
            
            String Gender = (String) regGender.getSelectedItem();
            pst.setString(7, Gender);
           
            pst.setString(8, regPhone.getText());
            pst.setString(9, regAddress.getText());
            pst.setString(10, regReligion.getText());
            pst.setString(11, regCitizenship.getText());
            
            String CivilStatus = (String) regCivilStatus.getSelectedItem();
            pst.setString(12, CivilStatus);
            
            pst.setString(13, regGuardian.getText());
            pst.setString(14, regPassword.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(bg, "You have successfully created an account. Please proceed to login.");
        }
        catch (SQLException ex) { System.out.println(ex.getMessage()); }
    }//GEN-LAST:event_regSignUpBtnActionPerformed

    private void regLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLoginActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
        
        dispose();
    }//GEN-LAST:event_regLoginActionPerformed

    private void regPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPasswordFocusGained
        if(regPassword.getText().equals("Enter password")) {
            regPassword.setText("");
            regPassword.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_regPasswordFocusGained

    private void regPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPasswordFocusLost
        if(regPassword.getText().equals("")) {
            regPassword.setText("Enter password");
            regPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_regPasswordFocusLost

    private void regPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPasswordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordMouseExited

    private void regPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField regAddress;
    private javax.swing.JLabel regAddress_label;
    private javax.swing.JTextField regBirthday_day;
    private javax.swing.JLabel regBirthday_label;
    private javax.swing.JTextField regBirthday_month;
    private javax.swing.JTextField regBirthday_year;
    private javax.swing.JTextField regCitizenship;
    private javax.swing.JLabel regCitizenship_label;
    private javax.swing.JLabel regCivilStat_label;
    private javax.swing.JComboBox<String> regCivilStatus;
    private javax.swing.JLabel regCopyright;
    private javax.swing.JTextField regEmail;
    private javax.swing.JLabel regEmail_label;
    private javax.swing.JTextField regFirstName;
    private javax.swing.JLabel regFirstName_label;
    private javax.swing.JComboBox<String> regGender;
    private javax.swing.JLabel regGender_label;
    private javax.swing.JTextField regGuardian;
    private javax.swing.JLabel regGuardian_label;
    private javax.swing.JTextField regLastName;
    private javax.swing.JLabel regLastName_label;
    private javax.swing.JButton regLogin;
    private javax.swing.JLabel regLogin_label;
    private javax.swing.JTextField regMidName;
    private javax.swing.JLabel regMidName_label;
    private javax.swing.JTextField regPassword;
    private javax.swing.JLabel regPassword_label;
    private javax.swing.JTextField regPhone;
    private javax.swing.JLabel regPhone_label;
    private javax.swing.JTextField regReligion;
    private javax.swing.JLabel regReligion_label;
    private javax.swing.JButton regSignUpBtn;
    private javax.swing.JTextField regStudNum;
    private javax.swing.JLabel regStudNum_label;
    private javax.swing.JLabel regTitle;
    // End of variables declaration//GEN-END:variables
}
